### ISSUE TITLE
gt.fit problem 

### ISSUE THREAD

**Issue by bigci10** [pysiakk/GeneticTree#30]
Hi When i try to fit data I'm getting an error " ValueError: Buffer dtype mismatch, expected 'SIZE_t' but got 'long'"

**Comment by pysiakk** [comment]
Hi. 

Thank you for the feedback.

Genetic Tree is a classification algorithm, so the training y input should be a numpy array with integers as labels. Please check if the type of your y input array elements is integer, not float. 

If it does not help, please describe a little closer the conditions under which this error occured: what did you input to the model, the traceback log, any information that would help us solve this problem.

Regards,
Karol

**Comment by bigci10** [comment]
Thank you for your interest.. my y input is already int and np.array....
I tried the example in the docs and again get this error 
![sonuc](https://user-images.githubusercontent.com/70436168/112217334-841f7c80-8bf0-11eb-842c-6364bbaac0d6.png)

**Comment by pysiakk** [comment]
Are you using Windows? Unfortunately, this package is not compatible with Windows yet. I recommend using VM with a Linux on it if you have only the Windows on you computer.
