### ISSUE TITLE
License declarations are inconsistent

### ISSUE THREAD

**Issue by kittentronic** [pysiakk/GeneticTree#32]
On the [Code page](https://github.com/pysiakk/GeneticTree) of this project the badge 'License: MIT' is displayed. However the license in the project's LICENSE file is not the [MIT license](https://mit-license.org/). The project's LICENSE file states 

> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense. It is prohibited 
> to sell or use this software in any commercial way.

which is self-contradictory: either permission is granted to deal in the software without restriction, or it is prohibited to sell or use the software commercially. If commercial use is allowed then the last sentence must be removed, and the text could be replaced with the actual MIT license if that is what is intended; if commercial use is not allowed then the text from 'without restriction' onwards must be changed so that it does not conflict with the last sentence, and this is definitely not an MIT license.

Subsequently the LICENSE file states that portions of the software are copied from scikit-learn and refers to that package's BSD 3-clause license. However the [text of that license](https://github.com/scikit-learn/scikit-learn/blob/main/COPYING) states

> Redistributions of source code must retain the above copyright notice, this
> list of conditions and the following disclaimer.

and these items are not included in the GeneticTree LICENSE file, which seems to be in violation of the scikit-learn license: I don't believe it's enough to simply link to the scikit-learn source or state that it carries the BSD 3-clause license.

If you want to (or are obliged to) prohibit commercial use of GeneticTree then I believe you need to remove the 'MIT' license badge and choose a self-consistent license text that accurately states what kinds of use are permitted, and you also need to include the full BSD 3-clause license text in order to comply with the license for the code you have copied from scikit-learn.

**Comment by pysiakk** [comment]
Hi. Thanks for the spotlight. License has been reviewed and changed to BSD-3 as code is based on the scikit-learn package. Scikit-learn developers added to the license text. If there are still some mistakes, please, point the out. Closing issue for now.
