### ISSUE TITLE
cythonize.py not found

### ISSUE THREAD

**Issue by berat-cakir** [pysiakk/GeneticTree#33]
The cythonize.py is not found. Unfortunately, I never build a setup.py so I hope you know more how to solve this issue.
I'm using Python 3.7.9 64-bit on windows 10 

`pip install genetic-tree
Collecting genetic-tree
  Using cached genetic-tree-0.1.0.tar.gz (909 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\berat\desktop\evorf\.venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Berat\\AppData\\Local\\Temp\\pip-install-rbmhg1ox\\genetic-tree_5c6b161120a24a3fb5d551c251c81358\\setup.py'"'"'; __file__='"'"'C:\\Users\\Berat\\AppData\\Local\\Temp\\pip-install-rbmhg1ox\\genetic-tree_5c6b161120a24a3fb5d551c251c81358\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Berat\AppData\Local\Temp\pip-pip-egg-info-jn4x0mhb'
       cwd: C:\Users\Berat\AppData\Local\Temp\pip-install-rbmhg1ox\genetic-tree_5c6b161120a24a3fb5d551c251c81358\
  Complete output (11 lines):
  C:\Users\Berat\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'C:\Users\Berat\AppData\Local\Temp\pip-install-rbmhg1ox\genetic-tree_5c6b161120a24a3fb5d551c251c81358\bin\cythonize.py': [Errno 2] No such file or directory
  Cythonizing sources
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Berat\AppData\Local\Temp\pip-install-rbmhg1ox\genetic-tree_5c6b161120a24a3fb5d551c251c81358\setup.py", line 150, in <module>
      setup_package()
    File "C:\Users\Berat\AppData\Local\Temp\pip-install-rbmhg1ox\genetic-tree_5c6b161120a24a3fb5d551c251c81358\setup.py", line 125, in setup_package
      generate_cython(root, "genetic_tree")
    File "C:\Users\Berat\AppData\Local\Temp\pip-install-rbmhg1ox\genetic-tree_5c6b161120a24a3fb5d551c251c81358\setup.py", line 49, in generate_cython
      raise RuntimeError("Running cythonize failed")
  RuntimeError: Running cythonize failed
WARNING: Discarding https://files.pythonhosted.org/packages/e8/f5/332581ee16a0d34e98e1166ff89c4516392a15a12fbadbe574f531521206/genetic-tree-0.1.0.tar.gz#sha256=ee374ea17fcb69b0ee701077627df10507539ff9635bd94b5d3b781977a3412f (from https://pypi.org/simple/genetic-tree/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement genetic-tree (from versions: 0.1.0)
ERROR: No matching distribution found for genetic-tree`

**Comment by pysiakk** [comment]
Hi. Thanks for the issue. The package was not prepared for Windows and this is probably the cause of this error. I encourage you to use this package in Linux environment only.
